# Generated by Django 4.2.7 on 2025-07-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
