# Generated by Django 4.2.7 on 2026-07-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_roomscan_detectedobject_roomrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_model_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_format',
            field=models.CharField(blank=True, default='glb', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='room_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='style_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RoomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled room design', max_length=200)),
                ('room_type', models.CharField(blank=True, default='living_room', max_length=100)),
                ('room_width', models.FloatField(default=4.0)),
                ('room_length', models.FloatField(default=5.0)),
                ('room_height', models.FloatField(default=2.7)),
                ('scene_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
