# Generated by Django 4.2.7 on 2026-07-06

from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_ar_model_url_product_color_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='products/models/',
                validators=[FileExtensionValidator(['glb'])],
            ),
        ),
    ]