# Generated by Django 4.2.7 on 2026-07-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_model_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomDesign',
        ),
    ]
