# Generated by Django 4.2.7 on 2026-07-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_roomdesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ar_model_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_3d_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_format',
        ),
    ]
