# Generated by Django 4.2.7 on 2026-07-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_ar_model_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style_tags',
        ),
    ]
